const foods = [
  { id: 1, name: "珍珠奶茶", type: "奶茶", emoji: "🧋", description: "香浓丝滑的奶茶配上Q弹珍珠，甜蜜暴击！", comment: "今日份快乐已到账~", calories: "约350大卡/杯", tags: ["下午茶", "续命水"], timePeriod: ["morning", "lunch", "dinner"] },
  { id: 2, name: "杨枝甘露", type: "奶茶", emoji: "🥭", description: "芒果西柚椰汁的完美组合，清甜解腻", comment: "甜品界的清流~", calories: "约280大卡/杯", tags: ["下午茶", "清爽"], timePeriod: ["lunch"] },
  { id: 3, name: "芋泥波波奶茶", type: "奶茶", emoji: "🧋", description: "绵密芋泥配Q弹波波，层次丰富", comment: "奶茶控的最爱！", calories: "约380大卡/杯", tags: ["下午茶", "网红"], timePeriod: ["morning", "lunch", "dinner"] },
  { id: 4, name: "椰椰拿铁", type: "奶茶", emoji: "🥥", description: "香浓咖啡配清爽椰汁，热带风情", comment: "异域风味很独特~", calories: "约250大卡/杯", tags: ["下午茶", "咖啡"], timePeriod: ["morning", "lunch"] },
  { id: 5, name: "波霸奶茶", type: "奶茶", emoji: "🧋", description: "大颗波霸配上香醇奶茶", comment: "大满足！", calories: "约400大卡/杯", tags: ["下午茶", "续命水"], timePeriod: ["morning", "lunch", "dinner"] },
  { id: 6, name: "茉莉奶绿", type: "奶茶", emoji: "🌸", description: "清新茉莉花香配丝滑牛奶", comment: "花香四溢~", calories: "约280大卡/杯", tags: ["下午茶", "清新"], timePeriod: ["morning", "lunch", "dinner"] },
  { id: 7, name: "红豆奶茶", type: "奶茶", emoji: "🧋", description: "软糯红豆配香浓奶茶，甜蜜暖心", comment: "红豆配奶茶，完美组合！", calories: "约350大卡/杯", tags: ["下午茶", "养生"], timePeriod: ["morning", "lunch", "dinner"] },
  { id: 8, name: "抹茶拿铁", type: "奶茶", emoji: "🍵", description: "日式抹茶配香浓牛奶，苦中带甜", comment: "日式小清新的味道~", calories: "约300大卡/杯", tags: ["下午茶", "健康"], timePeriod: ["morning", "lunch"] },
  { id: 9, name: "柠檬茶", type: "奶茶", emoji: "🍋", description: "清爽柠檬搭配醇厚茶底，酸甜解渴", comment: "夏日解暑神器！", calories: "约180大卡/杯", tags: ["下午茶", "清爽"], timePeriod: ["morning", "lunch", "dinner"] },
  { id: 10, name: "葡萄柚绿", type: "奶茶", emoji: "🍊", description: "西柚果肉与绿茶的清新组合", comment: "果粒多多超满足~", calories: "约220大卡/杯", tags: ["下午茶", "果茶"], timePeriod: ["morning", "lunch"] },
  { id: 11, name: "焦糖奶茶", type: "奶茶", emoji: "🍯", description: "香甜焦糖与浓郁奶茶的完美融合", comment: "甜蜜暴击！", calories: "约380大卡/杯", tags: ["下午茶", "甜品"], timePeriod: ["morning", "lunch", "dinner"] },
  { id: 12, name: "乌龙奶茶", type: "奶茶", emoji: "🧋", description: "醇厚乌龙茶配香浓牛奶", comment: "茶香浓郁超好喝~", calories: "约320大卡/杯", tags: ["下午茶", "茶香"], timePeriod: ["morning", "lunch", "dinner"] },
  { id: 13, name: "芒果奶茶", type: "奶茶", emoji: "🥭", description: "新鲜芒果泥配丝滑奶茶", comment: "热带水果的狂欢~", calories: "约350大卡/杯", tags: ["下午茶", "果茶"], timePeriod: ["morning", "lunch"] },
  { id: 14, name: "燕麦奶茶", type: "奶茶", emoji: "🌾", description: "健康燕麦配香浓奶茶", comment: "养生girl的首选~", calories: "约280大卡/杯", tags: ["健康", "轻体"], timePeriod: ["morning", "lunch"] },
  { id: 15, name: "桂花奶茶", type: "奶茶", emoji: "🌼", description: "芬芳桂花与醇香奶茶的邂逅", comment: "秋天的味道~", calories: "约300大卡/杯", tags: ["下午茶", "花香"], timePeriod: ["morning", "lunch", "dinner"] },
  { id: 16, name: "玫瑰奶茶", type: "奶茶", emoji: "🌹", description: "浪漫玫瑰花瓣配丝滑奶茶", comment: "少女心爆棚~", calories: "约290大卡/杯", tags: ["下午茶", "精致"], timePeriod: ["morning", "lunch"] },
  { id: 17, name: "珍珠红豆奶茶", type: "奶茶", emoji: "🧋", description: "双重料十足，珍珠红豆一次满足", comment: "双倍快乐！", calories: "约420大卡/杯", tags: ["下午茶", "管饱"], timePeriod: ["morning", "lunch", "dinner"] },
  { id: 18, name: "芝芝莓莓", type: "奶茶", emoji: "🍓", description: "新鲜草莓配浓郁芝士", comment: "颜值与实力并存！", calories: "约380大卡/杯", tags: ["网红", "下午茶"], timePeriod: ["morning", "lunch"] },
  { id: 19, name: "泰式奶茶", type: "奶茶", emoji: "🧋", description: "正宗泰式风味，浓郁香甜", comment: "异域风情满分！", calories: "约350大卡/杯", tags: ["网红", "下午茶"], timePeriod: ["morning", "lunch"] },
  { id: 20, name: "芋圆奶茶", type: "奶茶", emoji: "🧋", description: "软糯芋圆配香浓奶茶", comment: "Q弹有嚼劲~", calories: "约370大卡/杯", tags: ["下午茶", "小食"], timePeriod: ["morning", "lunch", "dinner"] },
  { id: 21, name: "烤奶", type: "奶茶", emoji: "🥛", description: "焦香烤奶风味，独特醇厚", comment: "炭火香气的奶茶~", calories: "约340大卡/杯", tags: ["下午茶", "特色"], timePeriod: ["morning", "lunch", "dinner"] },
  { id: 22, name: "茉莉奶盖", type: "奶茶", emoji: "🌿", description: "清新茉莉茶配浓郁奶盖", comment: "双重享受~", calories: "约360大卡/杯", tags: ["下午茶", "层次感"], timePeriod: ["morning", "lunch"] },
  { id: 23, name: "波波冰", type: "奶茶", emoji: "🧋", description: "凉爽冰沙配Q弹波波", comment: "夏日必备冰品！", calories: "约320大卡/杯", tags: ["消暑", "下午茶"], timePeriod: ["lunch", "dinner"] },
  { id: 24, name: "血糯米奶茶", type: "奶茶", emoji: "🧋", description: "健康血糯米配香浓奶茶", comment: "养生又美味~", calories: "约350大卡/杯", tags: ["养生", "健康"], timePeriod: ["morning", "lunch"] },
  { id: 25, name: "奥利奥奶茶", type: "奶茶", emoji: "🍪", description: "酥脆奥利奥配丝滑奶茶", comment: "童年回忆的味道！", calories: "约400大卡/杯", tags: ["下午茶", "甜品"], timePeriod: ["morning", "lunch", "dinner"] },
  { id: 26, name: "黑糖脏脏", type: "奶茶", emoji: "🧋", description: "黑糖挂壁配珍珠奶茶", comment: "网红爆款！", calories: "约420大卡/杯", tags: ["网红", "下午茶"], timePeriod: ["morning", "lunch"] },
  { id: 27, name: "芋泥波波2.0", type: "奶茶", emoji: "🧋", description: "升级版芋泥奶茶，更浓更香", comment: "芋泥控必点！", calories: "约390大卡/杯", tags: ["网红", "下午茶"], timePeriod: ["morning", "lunch"] },
  { id: 28, name: "伯爵奶茶", type: "奶茶", emoji: "🍵", description: "经典伯爵红茶配丝滑牛奶", comment: "英伦风情的优雅~", calories: "约280大卡/杯", tags: ["下午茶", "经典"], timePeriod: ["morning", "lunch"] },
  { id: 29, name: "巧克力奶茶", type: "奶茶", emoji: "🍫", description: "丝滑巧克力配香浓奶茶", comment: "甜蜜浓郁超幸福~", calories: "约380大卡/杯", tags: ["下午茶", "甜品"], timePeriod: ["morning", "lunch", "dinner"] },
  { id: 30, name: "抹茶红豆奶茶", type: "奶茶", emoji: "🍵", description: "抹茶与红豆的经典搭配", comment: "日式经典的完美结合~", calories: "约350大卡/杯", tags: ["下午茶", "日式"], timePeriod: ["morning", "lunch"] },
  { id: 31, name: "薄荷奶绿", type: "奶茶", emoji: "🌿", description: "清凉薄荷配清新奶绿", comment: "夏日清凉神器！", calories: "约260大卡/杯", tags: ["消暑", "清爽"], timePeriod: ["morning", "lunch"] },
  { id: 32, name: "红茶拿铁", type: "奶茶", emoji: "🧋", description: "浓郁红茶配香滑牛奶", comment: "经典港式风味~", calories: "约290大卡/杯", tags: ["下午茶", "经典"], timePeriod: ["morning", "lunch", "dinner"] },
  { id: 33, name: "桂花乌龙", type: "奶茶", emoji: "🌼", description: "桂花香与乌龙茶的融合", comment: "秋日限定的芬芳~", calories: "约270大卡/杯", tags: ["下午茶", "花香"], timePeriod: ["morning", "lunch", "dinner"] },
  { id: 34, name: "珍珠奶盖", type: "奶茶", emoji: "🧋", description: "Q弹珍珠配浓郁奶盖", comment: "双重口感的满足~", calories: "约390大卡/杯", tags: ["下午茶", "层次感"], timePeriod: ["morning", "lunch", "dinner"] },
  { id: 35, name: "芝士蛋糕", type: "甜品", emoji: "🍰", description: "绵密细腻的奶酪香气，入口即化的幸福感", comment: "甜甜的，心情美美哒~", calories: "约300大卡/块", tags: ["下午茶", "治愈系"], timePeriod: ["morning", "lunch"] },
  { id: 36, name: "豆花", type: "甜品", emoji: "🫘", description: "细腻嫩滑的豆香甜品，甜度可选", comment: "温柔的一天从这碗开始~", calories: "约120大卡/碗", tags: ["清淡", "养生"], timePeriod: ["morning", "lunch"] },
  { id: 37, name: "冰淇淋", type: "甜品", emoji: "🍦", description: "丝滑冰凉的甜蜜诱惑，夏日必备", comment: "冰冰凉，心飞扬~", calories: "约200大卡/球", tags: ["消暑", "治愈"], timePeriod: ["lunch", "dinner"] },
  { id: 38, name: "马卡龙", type: "甜品", emoji: "🧁", description: "精致法式小甜点，酥脆甜蜜", comment: "法式的浪漫与精致~", calories: "约100大卡/个", tags: ["精致", "下午茶"], timePeriod: ["lunch"] },
  { id: 39, name: "提拉米苏", type: "甜品", emoji: "🍰", description: "意式经典咖啡风味甜点", comment: "苦甜交织的美味~", calories: "约350大卡/份", tags: ["精致", "下午茶"], timePeriod: ["morning", "lunch"] },
  { id: 40, name: "芒果班戟", type: "甜品", emoji: "🥭", description: "软糯班戟皮包着香甜芒果", comment: "港式甜品的经典！", calories: "约280大卡/个", tags: ["下午茶", "港式"], timePeriod: ["morning", "lunch"] },
  { id: 41, name: "双皮奶", type: "甜品", emoji: "🥛", description: "细腻嫩滑的广式甜品", comment: "入口即化的温柔~", calories: "约180大卡/份", tags: ["养生", "清淡"], timePeriod: ["morning", "lunch"] },
  { id: 42, name: "榴莲忘返", type: "甜品", emoji: "🥭", description: "浓郁榴莲果肉配绵密冰淇淋", comment: "榴莲控的天堂！", calories: "约400大卡/份", tags: ["重口味", "下午茶"], timePeriod: ["lunch"] },
  { id: 43, name: "芒果千层", type: "甜品", emoji: "🥭", description: "层层叠加的芒果与奶油", comment: "芒果控的最爱！", calories: "约320大卡/块", tags: ["下午茶", "精致"], timePeriod: ["morning", "lunch"] },
  { id: 44, name: "雪媚娘", type: "甜品", emoji: "🍡", description: "软糯冰皮包着奶油水果", comment: "白白胖胖超可爱~", calories: "约200大卡/个", tags: ["下午茶", "可爱"], timePeriod: ["morning", "lunch"] },
  { id: 45, name: "红豆抹茶布丁", type: "甜品", emoji: "🍵", description: "抹茶布丁配软糯红豆", comment: "日式小清新的组合~", calories: "约220大卡/份", tags: ["下午茶", "日式"], timePeriod: ["morning", "lunch"] },
  { id: 46, name: "焦糖布丁", type: "甜品", emoji: "🍮", description: "丝滑布丁配焦糖酱", comment: "经典法式甜品~", calories: "约250大卡/份", tags: ["下午茶", "精致"], timePeriod: ["morning", "lunch"] },
  { id: 47, name: "巧克力熔岩蛋糕", type: "甜品", emoji: "🍫", description: "外酥内软巧克力流心", comment: "巧克力控必点！", calories: "约380大卡/个", tags: ["下午茶", "浓郁"], timePeriod: ["lunch"] },
  { id: 48, name: "泡芙", type: "甜品", emoji: "🥐", description: "酥脆外皮包着丝滑奶油", comment: "一口爆浆的快乐~", calories: "约200大卡/个", tags: ["下午茶", "小食"], timePeriod: ["morning", "lunch"] },
  { id: 49, name: "葡式蛋挞", type: "甜品", emoji: "🥧", description: "酥脆挞皮配嫩滑蛋芯", comment: "澳门经典美味~", calories: "约180大卡/个", tags: ["下午茶", "小食"], timePeriod: ["morning", "lunch"] },
  { id: 50, name: "抹茶大福", type: "甜品", emoji: "🍡", description: "抹茶风味软糯大福", comment: "日式甜品的精致~", calories: "约180大卡/个", tags: ["下午茶", "日式"], timePeriod: ["morning", "lunch"] },
  { id: 51, name: "慕斯蛋糕", type: "甜品", emoji: "🍰", description: "绵密慕斯入口即化", comment: "法式浪漫的滋味~", calories: "约280大卡/块", tags: ["精致", "下午茶"], timePeriod: ["morning", "lunch"] },
  { id: 52, name: "草莓拿破仑", type: "甜品", emoji: "🍓", description: "层层酥皮夹着奶油和草莓", comment: "颜值与美味并存~", calories: "约350大卡/份", tags: ["精致", "下午茶"], timePeriod: ["morning", "lunch"] },
  { id: 53, name: "黑森林蛋糕", type: "甜品", emoji: "🍒", description: "巧克力蛋糕配樱桃奶油", comment: "德国经典的甜蜜~", calories: "约320大卡/块", tags: ["下午茶", "经典"], timePeriod: ["morning", "lunch"] },
  { id: 54, name: "舒芙蕾", type: "甜品", emoji: "🍰", description: "云朵般轻盈的空气感甜点", comment: "入口即化的梦幻~", calories: "约280大卡/份", tags: ["精致", "下午茶"], timePeriod: ["morning", "lunch"] },
  { id: 55, name: "乳酪布丁", type: "甜品", emoji: "🍮", description: "绵密乳酪与嫩滑布丁", comment: "双重奶香超满足~", calories: "约220大卡/份", tags: ["下午茶", "嫩滑"], timePeriod: ["morning", "lunch"] },
  { id: 56, name: "芒果西米露", type: "甜品", emoji: "🥭", description: "香甜芒果配透明西米", comment: "热带风情甜品~", calories: "约240大卡/份", tags: ["下午茶", "清爽"], timePeriod: ["morning", "lunch"] },
  { id: 57, name: "芝士焗红薯", type: "甜品", emoji: "🍠", description: "香甜红薯配浓郁芝士", comment: "暖心暖胃的甜品~", calories: "约300大卡/份", tags: ["暖胃", "养生"], timePeriod: ["morning", "lunch"] },
  { id: 58, name: "抹茶红豆冰", type: "甜品", emoji: "🍵", description: "抹茶冰沙配红豆和冰淇淋", comment: "消暑又美味~", calories: "约320大卡/份", tags: ["消暑", "下午茶"], timePeriod: ["lunch"] },
  { id: 59, name: "椰汁西米糕", type: "甜品", emoji: "🥥", description: "清香椰汁配Q弹西米", comment: "泰式甜品的经典~", calories: "约200大卡/份", tags: ["下午茶", "清爽"], timePeriod: ["morning", "lunch"] },
  { id: 60, name: "栗子蒙布朗", type: "甜品", emoji: "🌰", description: "绵密栗子泥装饰的精致甜点", comment: "秋日限定的美味~", calories: "约300大卡/份", tags: ["精致", "季节限定"], timePeriod: ["morning", "lunch"] },
  { id: 61, name: "草莓大福", type: "甜品", emoji: "🍓", description: "新鲜草莓包在软糯外皮中", comment: "少女心爆棚~", calories: "约180大卡/个", tags: ["下午茶", "可爱"], timePeriod: ["morning", "lunch"] },
  { id: 62, name: "蛋黄酥", type: "甜品", emoji: "🥮", description: "层层酥皮包着咸蛋黄", comment: "中式甜点的经典~", calories: "约220大卡/个", tags: ["下午茶", "中式"], timePeriod: ["morning", "lunch"] },
  { id: 63, name: "绿豆糕", type: "甜品", emoji: "🟢", description: "细腻绿豆泥制作的传统糕点", comment: "清热解暑的传统美味~", calories: "约150大卡/个", tags: ["养生", "清淡"], timePeriod: ["morning", "lunch"] },
  { id: 64, name: "红丝绒蛋糕", type: "甜品", emoji: "🍰", description: "红色天鹅绒般的丝滑口感", comment: "高贵典雅的味道~", calories: "约320大卡/块", tags: ["精致", "下午茶"], timePeriod: ["morning", "lunch"] },
  { id: 65, name: "宫保鸡丁", type: "川菜", emoji: "🍗", description: "香辣开胃的花生鸡丁，下饭神器", comment: "干饭人的快乐源泉！", calories: "约450大卡/份", tags: ["下饭菜", "聚餐必备"], timePeriod: ["lunch", "dinner"] },
  { id: 66, name: "红烧肉", type: "川菜", emoji: "🥓", description: "肥而不腻的经典美味，入口即化", comment: "今天的快乐源泉！", calories: "约500大卡/份", tags: ["下饭菜", "硬菜"], timePeriod: ["lunch", "dinner"] },
  { id: 67, name: "麻辣香锅", type: "川菜", emoji: "🌶️", description: "香辣过瘾的炒制美食，食材丰富", comment: "香麻辣，三重暴击！", calories: "约500大卡/份", tags: ["下饭菜", "重口味"], timePeriod: ["lunch", "dinner"] },
  { id: 68, name: "酸菜鱼", type: "川菜", emoji: "🐟", description: "酸辣开胃的川味鱼类佳肴", comment: "酸酸辣辣就是爽~", calories: "约420大卡/份", tags: ["下饭菜", "开胃"], timePeriod: ["lunch", "dinner"] },
  { id: 69, name: "水煮牛肉", type: "川菜", emoji: "🥩", description: "麻辣鲜香的水煮牛肉片", comment: "无辣不欢~", calories: "约480大卡/份", tags: ["下饭菜", "重口味"], timePeriod: ["lunch", "dinner"] },
  { id: 70, name: "麻婆豆腐", type: "川菜", emoji: "🧆", description: "麻辣鲜香的经典川菜", comment: "下饭神器！", calories: "约280大卡/份", tags: ["下饭菜", "经典"], timePeriod: ["lunch", "dinner"] },
  { id: 71, name: "回锅肉", type: "川菜", emoji: "🥓", description: "香而不腻的经典川味", comment: "四川人的灵魂~", calories: "约400大卡/份", tags: ["下饭菜", "聚餐"], timePeriod: ["lunch", "dinner"] },
  { id: 72, name: "鱼香肉丝", type: "川菜", emoji: "🥩", description: "酸甜微辣的经典川菜", comment: "下饭神器！", calories: "约350大卡/份", tags: ["下饭菜", "经典"], timePeriod: ["lunch", "dinner"] },
  { id: 73, name: "水煮鱼", type: "川菜", emoji: "🐟", description: "麻辣鲜嫩的鱼肉料理", comment: "鱼肉爱好者的首选~", calories: "约480大卡/份", tags: ["聚餐", "硬菜"], timePeriod: ["lunch", "dinner"] },
  { id: 74, name: "毛血旺", type: "川菜", emoji: "🦆", description: "鸭血毛肚的麻辣盛宴", comment: "川渝名菜的代表~", calories: "约420大卡/份", tags: ["重口味", "聚餐"], timePeriod: ["lunch", "dinner"] },
  { id: 75, name: "辣子鸡", type: "川菜", emoji: "🍗", description: "干辣椒炒香酥鸡丁", comment: "香辣过瘾！", calories: "约380大卡/份", tags: ["下酒菜", "香辣"], timePeriod: ["lunch", "dinner"] },
  { id: 76, name: "口水鸡", type: "川菜", emoji: "🍗", description: "红油浇汁的鲜嫩鸡肉", comment: "麻辣鲜香开胃~", calories: "约320大卡/份", tags: ["开胃", "下饭菜"], timePeriod: ["lunch", "dinner"] },
  { id: 77, name: "夫妻肺片", type: "川菜", emoji: "🥩", description: "麻辣鲜香的红油凉菜", comment: "川菜凉菜经典~", calories: "约280大卡/份", tags: ["开胃", "下酒菜"], timePeriod: ["lunch", "dinner"] },
  { id: 78, name: "宫保虾球", type: "川菜", emoji: "🦐", description: "大虾配花生米的宫保风味", comment: "海鲜与川味的完美结合~", calories: "约350大卡/份", tags: ["下饭菜", "精致"], timePeriod: ["lunch", "dinner"] },
  { id: 79, name: "蚂蚁上树", type: "川菜", emoji: "🍝", description: "肉末粉丝的经典川菜", comment: "粉丝吸满汤汁超美味~", calories: "约300大卡/份", tags: ["下饭菜", "实惠"], timePeriod: ["lunch", "dinner"] },
  { id: 80, name: "干煸四季豆", type: "川菜", emoji: "🫛", description: "干香四溢的四季豆", comment: "下饭又健康~", calories: "约180大卡/份", tags: ["下饭菜", "素菜"], timePeriod: ["lunch", "dinner"] },
  { id: 81, name: "蒜泥白肉", type: "川菜", emoji: "🥩", description: "肥而不腻的蒜泥肉片", comment: "蒜香浓郁开胃~", calories: "约350大卡/份", tags: ["开胃", "下酒菜"], timePeriod: ["lunch", "dinner"] },
  { id: 82, name: "川北凉粉", type: "川菜", emoji: "🫕", description: "麻辣酸爽的凉粉", comment: "夏日开胃必备~", calories: "约150大卡/份", tags: ["开胃", "清凉"], timePeriod: ["lunch", "dinner"] },
  { id: 83, name: "担担面", type: "川菜", emoji: "🍜", description: "麻辣鲜香的面条", comment: "四川小吃经典~", calories: "约380大卡/碗", tags: ["主食", "小吃"], timePeriod: ["morning", "lunch", "dinner"] },
  { id: 84, name: "甜水面", type: "川菜", emoji: "🍜", description: "甜辣风味的面条", comment: "独特的甜辣口感~", calories: "约360大卡/碗", tags: ["主食", "特色"], timePeriod: ["morning", "lunch"] },
  { id: 85, name: "钟水饺", type: "川菜", emoji: "🥟", description: "红油浇汁的水饺", comment: "川式水饺的代表~", calories: "约280大卡/份", tags: ["小吃", "开胃"], timePeriod: ["morning", "lunch"] },
  { id: 86, name: "龙抄手", type: "川菜", emoji: "🥟", description: "皮薄馅嫩的馄饨", comment: "成都名小吃的经典~", calories: "约250大卡/份", tags: ["小吃", "清淡"], timePeriod: ["morning", "lunch"] },
  { id: 87, name: "宜宾燃面", type: "川菜", emoji: "🍜", description: "干香麻辣的宜宾特色面", comment: "燃面燃面，真的燃~", calories: "约400大卡/碗", tags: ["主食", "管饱"], timePeriod: ["morning", "lunch"] },
  { id: 88, name: "老麻抄手", type: "川菜", emoji: "🥟", description: "麻辣鲜香的抄手", comment: "麻得过瘾！", calories: "约280大卡/份", tags: ["小吃", "重口味"], timePeriod: ["morning", "lunch"] },
  { id: 89, name: "灯影牛肉", type: "川菜", emoji: "🥩", description: "薄如纸片的麻辣牛肉干", comment: "下酒神器！", calories: "约200大卡/份", tags: ["下酒菜", "零食"], timePeriod: ["lunch", "dinner"] },
  { id: 90, name: "樟茶鸭", type: "川菜", emoji: "🦆", description: "茶叶熏制的香酥鸭", comment: "四川名菜的经典~", calories: "约420大卡/份", tags: ["硬菜", "聚餐"], timePeriod: ["lunch", "dinner"] },
  { id: 91, name: "棒棒鸡", type: "川菜", emoji: "🍗", description: "麻辣红油浇汁的鸡肉", comment: "四川凉菜的代表~", calories: "约280大卡/份", tags: ["开胃", "下酒菜"], timePeriod: ["lunch", "dinner"] },
  { id: 92, name: "东坡肘子", type: "川菜", emoji: "🥩", description: "软糯入味的肘子肉", comment: "苏东坡的智慧~", calories: "约550大卡/份", tags: ["硬菜", "聚餐"], timePeriod: ["lunch", "dinner"] },
  { id: 93, name: "干锅花菜", type: "川菜", emoji: "🥦", description: "香辣入味的花菜", comment: "素菜也能很下饭~", calories: "约180大卡/份", tags: ["下饭菜", "素菜"], timePeriod: ["lunch", "dinner"] },
  { id: 94, name: "干锅土豆片", type: "川菜", emoji: "🥔", description: "焦香麻辣的土豆片", comment: "土豆控的最爱~", calories: "约220大卡/份", tags: ["下饭菜", "实惠"], timePeriod: ["lunch", "dinner"] },
  { id: 95, name: "黄焖鸡米饭", type: "快餐", emoji: "🍚", description: "软糯鸡肉配香喷喷米饭，份量十足", comment: "吃饱不想家~", calories: "约600大卡/份", tags: ["管饱", "实惠"], timePeriod: ["lunch", "dinner"] },
  { id: 96, name: "蛋炒饭", type: "快餐", emoji: "🍳", description: "金黄诱人的蛋香炒饭，粒粒分明", comment: "简单却经典的美味！", calories: "约450大卡/份", tags: ["管饱", "快手"], timePeriod: ["lunch", "dinner"] },
  { id: 97, name: "意式披萨", type: "快餐", emoji: "🍕", description: "芝士拉丝的意大利经典，馅料丰富", comment: "快乐多巴胺制造机！", calories: "约700大卡/份", tags: ["聚餐", "西式"], timePeriod: ["lunch", "dinner"] },
  { id: 98, name: "汉堡薯条", type: "快餐", emoji: "🍔", description: "经典美式快餐组合，快乐源泉", comment: "垃圾食品最快乐！", calories: "约650大卡/份", tags: ["快餐", "解压"], timePeriod: ["lunch", "dinner"] },
  { id: 99, name: "炸鸡汉堡", type: "快餐", emoji: "🍗", description: "香脆炸鸡配汉堡面包", comment: "快餐也能很美味~", calories: "约550大卡/份", tags: ["快餐", "解压"], timePeriod: ["lunch", "dinner"] },
  { id: 100, name: "炸鸡排饭", type: "快餐", emoji: "🍗", description: "香脆鸡排配米饭套餐", comment: "能量满满的午餐~", calories: "约650大卡/份", tags: ["管饱", "快餐"], timePeriod: ["lunch", "dinner"] },
  { id: 101, name: "咖喱鸡肉饭", type: "快餐", emoji: "🍛", description: "浓郁咖喱配嫩滑鸡肉", comment: "异域风情的快餐~", calories: "约580大卡/份", tags: ["管饱", "下饭"], timePeriod: ["lunch", "dinner"] },
  { id: 102, name: "照烧鸡腿饭", type: "快餐", emoji: "🍗", description: "甜咸照烧酱配鸡腿", comment: "日式快餐的经典~", calories: "约600大卡/份", tags: ["管饱", "日式"], timePeriod: ["lunch", "dinner"] },
  { id: 103, name: "牛肉盖浇饭", type: "快餐", emoji: "🥩", description: "浓郁牛肉配米饭", comment: "简单却美味~", calories: "约550大卡/份", tags: ["管饱", "实惠"], timePeriod: ["lunch", "dinner"] },
  { id: 104, name: "红烧牛肉面", type: "快餐", emoji: "🍜", description: "软烂牛肉配劲道面条", comment: "一碗满足~", calories: "约550大卡/碗", tags: ["管饱", "主食"], timePeriod: ["morning", "lunch", "dinner"] },
  { id: 105, name: "酸辣粉", type: "快餐", emoji: "🍜", description: "酸辣开胃的红薯粉", comment: "开胃解馋的快餐~", calories: "约350大卡/碗", tags: ["开胃", "重口味"], timePeriod: ["lunch", "dinner"] },
  { id: 106, name: "鸡块薯条套餐", type: "快餐", emoji: "🍟", description: "香脆鸡块配薯条可乐", comment: "经典快餐组合~", calories: "约700大卡/份", tags: ["快餐", "解压"], timePeriod: ["lunch", "dinner"] },
  { id: 107, name: "墨西哥鸡肉卷", type: "快餐", emoji: "🌯", description: "香辣鸡肉配蔬菜卷饼", comment: "异域风情的快餐~", calories: "约450大卡/份", tags: ["轻食", "便捷"], timePeriod: ["lunch"] },
  { id: 108, name: "沙县小吃套餐", type: "快餐", emoji: "🥟", description: "蒸饺拌面套餐", comment: "实惠快餐的选择~", calories: "约500大卡/份", tags: ["管饱", "实惠"], timePeriod: ["morning", "lunch"] },
  { id: 109, name: "麻辣香锅套餐", type: "快餐", emoji: "🌶️", description: "自选食材麻辣炒制", comment: "随心所欲的美味~", calories: "约550大卡/份", tags: ["管饱", "重口味"], timePeriod: ["lunch", "dinner"] },
  { id: 110, name: "煲仔饭", type: "快餐", emoji: "🍚", description: "锅巴香脆的煲仔饭", comment: "广东经典快餐~", calories: "约580大卡/份", tags: ["管饱", "粤式"], timePeriod: ["lunch", "dinner"] },
  { id: 111, name: "铁板炒饭", type: "快餐", emoji: "🍳", description: "铁板滋滋作响的炒饭", comment: "香气四溢~", calories: "约500大卡/份", tags: ["管饱", "快手"], timePeriod: ["lunch", "dinner"] },
  { id: 112, name: "炒牛河", type: "快餐", emoji: "🥢", description: "牛肉片炒河粉", comment: "广东经典主食~", calories: "约480大卡/份", tags: ["管饱", "粤式"], timePeriod: ["morning", "lunch", "dinner"] },
  { id: 113, name: "叉烧饭", type: "快餐", emoji: "🥩", description: "蜜汁叉烧配米饭", comment: "港式茶餐厅经典~", calories: "约550大卡/份", tags: ["管饱", "港式"], timePeriod: ["morning", "lunch"] },
  { id: 114, name: "盖浇面", type: "快餐", emoji: "🍜", description: "浇头丰富的面条", comment: "面食主义者的选择~", calories: "约500大卡/碗", tags: ["管饱", "主食"], timePeriod: ["morning", "lunch", "dinner"] },
  { id: 115, name: "炒饼丝", type: "快餐", emoji: "🫓", description: "烙饼切丝翻炒", comment: "北方经典快餐~", calories: "约450大卡/份", tags: ["管饱", "实惠"], timePeriod: ["morning", "lunch"] },
  { id: 116, name: "烩面", type: "快餐", emoji: "🍜", description: "宽厚面条配浓郁汤底", comment: "河南经典面食~", calories: "约500大卡/碗", tags: ["管饱", "暖胃"], timePeriod: ["morning", "lunch"] },
  { id: 117, name: "热干面", type: "快餐", emoji: "🍜", description: "芝麻酱拌的热干面", comment: "武汉早餐的代表~", calories: "约450大卡/碗", tags: ["早点", "管饱"], timePeriod: ["morning"] },
  { id: 118, name: "biangbiang面", type: "快餐", emoji: "🍜", description: "宽厚的陕西特色面", comment: "裤带面的霸气~", calories: "约550大卡/碗", tags: ["管饱", "西北"], timePeriod: ["morning", "lunch"] },
  { id: 119, name: "牛肉拉面", type: "快餐", emoji: "🍜", description: "手工拉面配牛肉片", comment: "兰州拉面的正宗~", calories: "约500大卡/碗", tags: ["管饱", "西北"], timePeriod: ["morning", "lunch"] },
  { id: 120, name: "炸酱面", type: "快餐", emoji: "🍜", description: "浓郁炸酱拌面条", comment: "老北京的味道~", calories: "约480大卡/碗", tags: ["管饱", "京味"], timePeriod: ["morning", "lunch"] },
  { id: 121, name: "重庆老火锅", type: "火锅", emoji: "🔥", description: "正宗重庆风味，热辣过瘾的牛油火锅", comment: "没有什么是一顿火锅解决不了的！", calories: "约800大卡/份", tags: ["聚餐", "热闹"], timePeriod: ["lunch", "dinner"] },
  { id: 122, name: "潮汕牛肉火锅", type: "火锅", emoji: "🥩", description: "新鲜牛肉的极致美味", comment: "鲜牛肉火锅的经典~", calories: "约600大卡/份", tags: ["聚餐", "清淡"], timePeriod: ["lunch", "dinner"] },
  { id: 123, name: "老北京铜锅涮肉", type: "火锅", emoji: "🍲", description: "传统铜锅涮鲜羊肉", comment: "老北京的味道~", calories: "约550大卡/份", tags: ["聚餐", "传统"], timePeriod: ["lunch", "dinner"] },
  { id: 124, name: "菌菇火锅", type: "火锅", emoji: "🍄", description: "各种菌菇的鲜美汤底", comment: "养生火锅的首选~", calories: "约400大卡/份", tags: ["养生", "清淡"], timePeriod: ["lunch", "dinner"] },
  { id: 125, name: "番茄火锅", type: "火锅", emoji: "🍅", description: "浓郁番茄汤底的火锅", comment: "酸甜开胃~", calories: "约450大卡/份", tags: ["清淡", "开胃"], timePeriod: ["lunch", "dinner"] },
  { id: 126, name: "猪肚鸡火锅", type: "火锅", emoji: "🐔", description: "猪肚配鸡肉的养生火锅", comment: "暖胃又暖心~", calories: "约500大卡/份", tags: ["养生", "暖胃"], timePeriod: ["lunch", "dinner"] },
  { id: 127, name: "鱼头火锅", type: "火锅", emoji: "🐟", description: "大鱼头的鲜美火锅", comment: "鱼肉爱好者的首选~", calories: "约480大卡/份", tags: ["聚餐", "鲜嫩"], timePeriod: ["lunch", "dinner"] },
  { id: 128, name: "澳门豆捞", type: "火锅", emoji: "🍲", description: "港式风味的小火锅", comment: "精致火锅的代表~", calories: "约450大卡/份", tags: ["精致", "聚餐"], timePeriod: ["lunch", "dinner"] },
  { id: 129, name: "日式寿喜烧", type: "火锅", emoji: "🍲", description: "日式甜酱油汤底的牛肉锅", comment: "日式火锅的经典~", calories: "约550大卡/份", tags: ["日式", "精致"], timePeriod: ["lunch", "dinner"] },
  { id: 130, name: "韩国部队火锅", type: "火锅", emoji: "🍲", description: "韩式辣酱配丰富食材", comment: "韩剧同款的快乐~", calories: "约520大卡/份", tags: ["聚餐", "热闹"], timePeriod: ["lunch", "dinner"] },
  { id: 131, name: "泰国冬阴功火锅", type: "火锅", emoji: "🍲", description: "酸辣泰式风味的火锅", comment: "异域风情的美味~", calories: "约480大卡/份", tags: ["开胃", "重口味"], timePeriod: ["lunch", "dinner"] },
  { id: 132, name: "粥底火锅", type: "火锅", emoji: "🥣", description: "绵密粥底涮各种食材", comment: "清淡养生的选择~", calories: "约400大卡/份", tags: ["养生", "清淡"], timePeriod: ["lunch", "dinner"] },
  { id: 133, name: "椰子鸡火锅", type: "火锅", emoji: "🥥", description: "椰子水做汤底的鸡肉锅", comment: "清爽甘甜~", calories: "约420大卡/份", tags: ["养生", "清淡"], timePeriod: ["lunch", "dinner"] },
  { id: 134, name: "驴肉火锅", type: "火锅", emoji: "🐴", description: "新鲜驴肉的特色火锅", comment: "地方特色的美味~", calories: "约500大卡/份", tags: ["特色", "聚餐"], timePeriod: ["lunch", "dinner"] },
  { id: 135, name: "鹅肠火锅", type: "火锅", emoji: "🦢", description: "新鲜鹅肠的麻辣火锅", comment: "川渝火锅的经典~", calories: "约480大卡/份", tags: ["重口味", "聚餐"], timePeriod: ["lunch", "dinner"] },
  { id: 136, name: "黄喉火锅", type: "火锅", emoji: "🦴", description: "脆嫩黄喉的火锅", comment: "口感独特的美味~", calories: "约350大卡/份", tags: ["特色", "脆嫩"], timePeriod: ["lunch", "dinner"] },
  { id: 137, name: "鸭血火锅", type: "火锅", emoji: "🩸", description: "嫩滑鸭血的火锅", comment: "火锅必点~", calories: "约280大卡/份", tags: ["实惠", "嫩滑"], timePeriod: ["lunch", "dinner"] },
  { id: 138, name: "虾滑火锅", type: "火锅", emoji: "🦐", description: "手打虾滑的鲜美火锅", comment: "虾控的最爱~", calories: "约380大卡/份", tags: ["精致", "鲜嫩"], timePeriod: ["lunch", "dinner"] },
  { id: 139, name: "毛肚火锅", type: "火锅", emoji: "🦠", description: "七上八下的鲜毛肚", comment: "川渝火锅的灵魂~", calories: "约300大卡/份", tags: ["经典", "必点"], timePeriod: ["lunch", "dinner"] },
  { id: 140, name: "腰片火锅", type: "火锅", emoji: "🥩", description: "鲜嫩猪腰的火锅", comment: "口感独特的美味~", calories: "约320大卡/份", tags: ["特色", "聚餐"], timePeriod: ["lunch", "dinner"] },
  { id: 141, name: "牛百叶火锅", type: "火锅", emoji: "🦠", description: "爽脆牛百叶的火锅", comment: "脆嫩可口的美味~", calories: "约280大卡/份", tags: ["实惠", "脆嫩"], timePeriod: ["lunch", "dinner"] },
  { id: 142, name: "羊肉卷火锅", type: "火锅", emoji: "🥩", description: "薄切羊肉卷的涮锅", comment: "冬日暖身的经典~", calories: "约480大卡/份", tags: ["聚餐", "暖身"], timePeriod: ["lunch", "dinner"] },
  { id: 143, name: "肥牛卷火锅", type: "火锅", emoji: "🥩", description: "精选肥牛的涮锅", comment: "牛肉控的盛宴~", calories: "约520大卡/份", tags: ["聚餐", "硬菜"], timePeriod: ["lunch", "dinner"] },
  { id: 144, name: "鱼丸火锅", type: "火锅", emoji: "🐟", description: "Q弹鱼丸的火锅", comment: "老少皆宜的美味~", calories: "约350大卡/份", tags: ["清淡", "弹牙"], timePeriod: ["lunch", "dinner"] },
  { id: 145, name: "牛肉丸火锅", type: "火锅", emoji: "🥩", description: "手打牛肉丸的火锅", comment: "潮汕火锅的代表~", calories: "约400大卡/份", tags: ["聚餐", "弹牙"], timePeriod: ["lunch", "dinner"] },
  { id: 146, name: "烤鱼", type: "烧烤", emoji: "🐟", description: "外焦里嫩的香烤鱼类，配菜丰富", comment: "今晚吃鱼，明天有余~", calories: "约550大卡/份", tags: ["聚餐", "硬菜"], timePeriod: ["lunch", "dinner"] },
  { id: 147, name: "炭火烤串", type: "烧烤", emoji: "🍖", description: "滋滋冒油的炭火烤串，午餐工作餐首选", comment: "今晚撸串，不醉不归！", calories: "约450大卡/份", tags: ["夜宵", "聚餐"], timePeriod: ["lunch", "dinner"] },
  { id: 148, name: "羊肉串", type: "烧烤", emoji: "🍢", description: "孜然飘香的烤羊肉", comment: "撸串的经典~", calories: "约150大卡/串", tags: ["夜宵", "下酒"], timePeriod: ["dinner"] },
  { id: 149, name: "牛肉串", type: "烧烤", emoji: "🍢", description: "鲜嫩多汁的烤牛肉", comment: "肉食者的最爱~", calories: "约120大卡/串", tags: ["夜宵", "聚餐"], timePeriod: ["dinner"] },
  { id: 150, name: "烤鸡翅", type: "烧烤", emoji: "🍗", description: "香脆诱人的烤鸡翅", comment: "大小朋友都爱~", calories: "约180大卡/个", tags: ["夜宵", "解馋"], timePeriod: ["dinner"] },
  { id: 151, name: "烤五花肉", type: "烧烤", emoji: "🥓", description: "肥瘦相间的烤五花", comment: "滋滋冒油的美味~", calories: "约200大卡/串", tags: ["夜宵", "聚餐"], timePeriod: ["dinner"] },
  { id: 152, name: "烤生蚝", type: "烧烤", emoji: "🦪", description: "蒜蓉烤生蚝的鲜美", comment: "海鲜烧烤的代表~", calories: "约100大卡/个", tags: ["夜宵", "精致"], timePeriod: ["dinner"] },
  { id: 153, name: "烤扇贝", type: "烧烤", emoji: "🐚", description: "蒜蓉烤扇贝的鲜嫩", comment: "海鲜控的最爱~", calories: "约80大卡/个", tags: ["夜宵", "精致"], timePeriod: ["dinner"] },
  { id: 154, name: "烤茄子", type: "烧烤", emoji: "🍆", description: "蒜香烤茄子的软糯", comment: "素菜烧烤的经典~", calories: "约80大卡/个", tags: ["夜宵", "健康"], timePeriod: ["dinner"] },
  { id: 155, name: "烤韭菜", type: "烧烤", emoji: "🥬", description: "孜然烤韭菜的香气", comment: "下酒神器~", calories: "约60大卡/份", tags: ["夜宵", "下酒"], timePeriod: ["dinner"] },
  { id: 156, name: "烤金针菇", type: "烧烤", emoji: "🍄", description: "蒜蓉烤金针菇", comment: "菌菇烧烤的美味~", calories: "约50大卡/份", tags: ["夜宵", "清淡"], timePeriod: ["dinner"] },
  { id: 157, name: "烤香菇", type: "烧烤", emoji: "🍄", description: "香菇的鲜美烧烤", comment: "菌香四溢~", calories: "约60大卡/个", tags: ["夜宵", "健康"], timePeriod: ["dinner"] },
  { id: 158, name: "烤玉米", type: "烧烤", emoji: "🌽", description: "香甜软糯的烤玉米", comment: "粗粮烧烤的健康选择~", calories: "约120大卡/个", tags: ["夜宵", "健康"], timePeriod: ["dinner"] },
  { id: 159, name: "烤红薯", type: "烧烤", emoji: "🍠", description: "香甜软糯的烤红薯", comment: "冬日街头的温暖~", calories: "约180大卡/个", tags: ["夜宵", "暖胃"], timePeriod: ["dinner"] },
  { id: 160, name: "烤土豆", type: "烧烤", emoji: "🥔", description: "外焦里嫩的烤土豆", comment: "朴实却美味~", calories: "约150大卡/个", tags: ["夜宵", "实惠"], timePeriod: ["dinner"] },
  { id: 161, name: "烤馒头片", type: "烧烤", emoji: "🥖", description: "香脆的烤馒头片", comment: "简单却好吃的宵夜~", calories: "约100大卡/串", tags: ["夜宵", "实惠"], timePeriod: ["dinner"] },
  { id: 162, name: "烤鸡胗", type: "烧烤", emoji: "🐔", description: "脆嫩有嚼劲的烤鸡胗", comment: "下酒的绝配~", calories: "约80大卡/串", tags: ["夜宵", "下酒"], timePeriod: ["dinner"] },
  { id: 163, name: "烤鸡心", type: "烧烤", emoji: "❤️", description: "鲜嫩烤鸡心的美味", comment: "内脏控的最爱~", calories: "约70大卡/串", tags: ["夜宵", "重口味"], timePeriod: ["dinner"] },
  { id: 164, name: "烤板筋", type: "烧烤", emoji: "🦴", description: "弹牙有嚼劲的烤板筋", comment: "嚼劲十足~", calories: "约90大卡/串", tags: ["夜宵", "下酒"], timePeriod: ["dinner"] },
  { id: 165, name: "烤大腰子", type: "烧烤", emoji: "🥜", description: "滋补烤猪腰的美味", comment: "以形补形~", calories: "约150大卡/串", tags: ["夜宵", "滋补"], timePeriod: ["dinner"] },
  { id: 166, name: "烤虾", type: "烧烤", emoji: "🦐", description: "鲜甜可口的烤大虾", comment: "海鲜烧烤的经典~", calories: "约60大卡/只", tags: ["夜宵", "精致"], timePeriod: ["dinner"] },
  { id: 167, name: "烤鱿鱼", type: "烧烤", emoji: "🦑", description: "铁板烤鱿鱼的Q弹", comment: "夜市的热门~", calories: "约120大卡/份", tags: ["夜宵", "弹牙"], timePeriod: ["dinner"] },
  { id: 168, name: "烤带子", type: "烧烤", emoji: "🐚", description: "蒜蓉烤带子的鲜美", comment: "海鲜控的最爱~", calories: "约100大卡/个", tags: ["夜宵", "精致"], timePeriod: ["dinner"] },
  { id: 169, name: "烤秋刀鱼", type: "烧烤", emoji: "🐟", description: "盐烤秋刀鱼的鲜香", comment: "日式烧烤的经典~", calories: "约150大卡/条", tags: ["夜宵", "日式"], timePeriod: ["dinner"] },
  { id: 170, name: "烤三文鱼头", type: "烧烤", emoji: "🐟", description: "盐烤三文鱼头的醇香", comment: "日料控的最爱~", calories: "约200大卡/份", tags: ["夜宵", "日式"], timePeriod: ["dinner"] },
  { id: 171, name: "日式烤肉", type: "日料", emoji: "🥩", description: "精选和牛的日式烤肉，入口即化", comment: "日料的极致享受~", calories: "约600大卡/份", tags: ["聚餐", "精致"], timePeriod: ["lunch", "dinner"] },
  { id: 172, name: "三文鱼刺身", type: "日料", emoji: "🍣", description: "新鲜三文鱼切片，鲜美嫩滑", comment: "海洋的味道~", calories: "约280大卡/份", tags: ["轻食", "健康"], timePeriod: ["lunch", "dinner"] },
  { id: 173, name: "鳗鱼饭", type: "日料", emoji: "🍱", description: "蒲烧鳗鱼配香喷喷米饭", comment: "日式便当的经典~", calories: "约550大卡/份", tags: ["主食", "精致"], timePeriod: ["lunch", "dinner"] },
  { id: 174, name: "猪排饭", type: "日料", emoji: "🍛", description: "酥脆猪排配滑蛋的日式饭", comment: "日式定食的代表~", calories: "约650大卡/份", tags: ["主食", "管饱"], timePeriod: ["lunch"] },
  { id: 175, name: "牛肉饭", type: "日料", emoji: "🍛", description: "肥牛片配温泉蛋的日式饭", comment: "盖浇饭的日式版本~", calories: "约580大卡/份", tags: ["主食", "便捷"], timePeriod: ["lunch"] },
  { id: 176, name: "亲子饭", type: "日料", emoji: "🍛", description: "鸡肉和鸡蛋的温馨组合", comment: "日式家常的美味~", calories: "约520大卡/份", tags: ["主食", "清淡"], timePeriod: ["lunch"] },
  { id: 177, name: "天妇罗", type: "日料", emoji: "🍤", description: "酥脆外壳的炸海鲜蔬菜", comment: "日式炸物的经典~", calories: "约350大卡/份", tags: ["小吃", "精致"], timePeriod: ["lunch"] },
  { id: 178, name: "炸猪排", type: "日料", emoji: "🥩", description: "外酥里嫩的日式炸猪排", comment: "日式快餐的代表~", calories: "约550大卡/份", tags: ["主食", "管饱"], timePeriod: ["lunch"] },
  { id: 179, name: "味噌汤", type: "日料", emoji: "🍲", description: "日式味噌汤的鲜香", comment: "日式料理的灵魂~", calories: "约80大卡/碗", tags: ["汤品", "清淡"], timePeriod: ["morning", "lunch", "dinner"] },
  { id: 180, name: "味噌拉面", type: "日料", emoji: "🍜", description: "浓郁味噌汤底的拉面", comment: "寒冷冬日的暖心~", calories: "约550大卡/碗", tags: ["主食", "暖胃"], timePeriod: ["lunch", "dinner"] },
  { id: 181, name: "酱油拉面", type: "日料", emoji: "🍜", description: "清汤酱油风味的拉面", comment: "日式拉面的经典~", calories: "约500大卡/碗", tags: ["主食", "清淡"], timePeriod: ["lunch", "dinner"] },
  { id: 182, name: "豚骨拉面", type: "日料", emoji: "🍜", description: "浓郁豚骨汤底的拉面", comment: "拉面控的最爱~", calories: "约600大卡/碗", tags: ["主食", "浓郁"], timePeriod: ["lunch", "dinner"] },
  { id: 183, name: "乌冬面", type: "日料", emoji: "🍜", description: "粗滑劲道的日式乌冬", comment: "日式面食的代表~", calories: "约450大卡/碗", tags: ["主食", "管饱"], timePeriod: ["morning", "lunch", "dinner"] },
  { id: 184, name: "荞麦面", type: "日料", emoji: "🍜", description: "清爽健康的日式荞麦面", comment: "夏日清新的选择~", calories: "约380大卡/碗", tags: ["主食", "清淡"], timePeriod: ["morning", "lunch"] },
  { id: 185, name: "茶泡饭", type: "日料", emoji: "🍵", description: "茶汤泡饭的清淡美味", comment: "日式家常的简单~", calories: "约300大卡/份", tags: ["主食", "清淡"], timePeriod: ["morning", "lunch"] },
  { id: 186, name: "蛋包饭", type: "日料", emoji: "🍳", description: "嫩滑蛋皮包着炒饭", comment: "可爱又美味~", calories: "约550大卡/份", tags: ["主食", "可爱"], timePeriod: ["lunch"] },
  { id: 187, name: "大阪烧", type: "日料", emoji: "🥞", description: "日式蔬菜煎饼的美味", comment: "大阪街头的味道~", calories: "约450大卡/份", tags: ["小吃", "聚餐"], timePeriod: ["lunch", "dinner"] },
  { id: 188, name: "章鱼小丸子", type: "日料", emoji: "🐙", description: "外酥内软的章鱼小丸子", comment: "日本动漫的经典~", calories: "约200大卡/份", tags: ["小吃", "下午茶"], timePeriod: ["lunch"] },
  { id: 189, name: "铜锣烧", type: "日料", emoji: "🥯", description: "红豆馅的日式小饼", comment: "哆啦A梦的最爱~", calories: "约180大卡/个", tags: ["小吃", "下午茶"], timePeriod: ["morning", "lunch"] },
  { id: 190, name: "部队火锅", type: "韩料", emoji: "🍲", description: "韩式辣酱配丰富配菜的火锅", comment: "韩剧同款快乐~", calories: "约550大卡/份", tags: ["聚餐", "热闹"], timePeriod: ["lunch", "dinner"] },
  { id: 191, name: "石锅拌饭", type: "韩料", emoji: "🍚", description: "香喷喷的石锅饭配韩式辣酱", comment: "韩式经典~", calories: "约480大卡/份", tags: ["管饱", "实惠"], timePeriod: ["lunch"] },
  { id: 192, name: "烤肉拌饭", type: "韩料", emoji: "🍖", description: "香喷喷烤肉配米饭", comment: "韩国快餐的代表~", calories: "约600大卡/份", tags: ["主食", "管饱"], timePeriod: ["lunch"] },
  { id: 193, name: "芝士排骨", type: "韩料", emoji: "🦴", description: "拉丝芝士配香辣排骨", comment: "网红韩料的经典~", calories: "约650大卡/份", tags: ["聚餐", "网红"], timePeriod: ["lunch", "dinner"] },
  { id: 194, name: "参鸡汤", type: "韩料", emoji: "🐔", description: "人参炖鸡的养生汤", comment: "韩国传统养生~", calories: "约450大卡/份", tags: ["养生", "暖胃"], timePeriod: ["lunch"] },
  { id: 195, name: "韩式炸鸡", type: "韩料", emoji: "🍗", description: "甜辣酱裹着的炸鸡", comment: "韩剧标配美食~", calories: "约550大卡/份", tags: ["聚餐", "下酒"], timePeriod: ["lunch", "dinner"] },
  { id: 196, name: "辣炒年糕", type: "韩料", emoji: "🍡", description: "甜辣年糕的Q弹美味", comment: "韩国街头小吃的经典~", calories: "约350大卡/份", tags: ["小吃", "开胃"], timePeriod: ["lunch"] },
  { id: 197, name: "韩式冷面", type: "韩料", emoji: "🍜", description: "冰凉酸甜的荞麦面", comment: "夏日消暑的美味~", calories: "约380大卡/碗", tags: ["主食", "清凉"], timePeriod: ["morning", "lunch"] },
  { id: 198, name: "拌饭", type: "韩料", emoji: "🍚", description: "各种蔬菜拌米饭", comment: "简单却营养~", calories: "约500大卡/份", tags: ["主食", "健康"], timePeriod: ["lunch"] },
  { id: 199, name: "韩式泡面", type: "韩料", emoji: "🍜", description: "韩式方便面的美味", comment: "深夜食堂的首选~", calories: "约450大卡/碗", tags: ["主食", "便捷"], timePeriod: ["lunch", "dinner"] },
  { id: 200, name: "炒杂菜", type: "韩料", emoji: "🥬", description: "韩式粉丝炒蔬菜", comment: "韩式家常的美味~", calories: "约280大卡/份", tags: ["小吃", "清淡"], timePeriod: ["lunch"] },
  { id: 201, name: "泡菜饼", type: "韩料", emoji: "🥞", description: "泡菜风味的韩式煎饼", comment: "下酒的好搭档~", calories: "约280大卡/份", tags: ["小吃", "下酒"], timePeriod: ["lunch"] },
  { id: 202, name: "海鲜葱饼", type: "韩料", emoji: "🥞", description: "海鲜蔬菜的韩式煎饼", comment: "酥脆鲜香~", calories: "约320大卡/份", tags: ["小吃", "聚餐"], timePeriod: ["lunch"] },
  { id: 203, name: "芝士炒饭", type: "韩料", emoji: "🍚", description: "拉丝芝士配炒饭", comment: "拉丝诱惑~", calories: "约550大卡/份", tags: ["主食", "浓郁"], timePeriod: ["lunch"] },
  { id: 204, name: "韩式炸酱面", type: "韩料", emoji: "🍜", description: "甜面酱拌面条的中韩混血", comment: "独特的甜咸口味~", calories: "约480大卡/碗", tags: ["主食", "便捷"], timePeriod: ["morning", "lunch"] },
  { id: 205, name: "猪骨汤", type: "韩料", emoji: "🦴", description: "浓郁猪骨熬制的汤", comment: "暖身暖胃的美味~", calories: "约400大卡/份", tags: ["暖胃", "养生"], timePeriod: ["morning", "lunch"] },
  { id: 206, name: "豆芽汤", type: "韩料", emoji: "🥣", description: "清新的豆芽汤", comment: "解酒养胃的美味~", calories: "约150大卡/份", tags: ["清淡", "养生"], timePeriod: ["morning"] },
  { id: 207, name: "泡菜汤", type: "韩料", emoji: "🥬", description: "酸辣开胃的泡菜汤", comment: "韩国家常的经典~", calories: "约180大卡/份", tags: ["开胃", "重口味"], timePeriod: ["morning", "lunch"] },
  { id: 208, name: "油条豆浆", type: "面点", emoji: "🥖", description: "酥脆油条配香浓豆浆，经典中式早餐", comment: "传统早餐的精髓~", calories: "约400大卡/份", tags: ["早点", "管饱"], timePeriod: ["morning"] },
  { id: 209, name: "皮蛋瘦肉粥", type: "面点", emoji: "🥣", description: "绵密温润的咸粥，养胃又暖心", comment: "清晨的温柔呵护~", calories: "约200大卡/碗", tags: ["清淡", "养生"], timePeriod: ["morning"] },
  { id: 210, name: "兰州拉面", type: "面点", emoji: "🍜", description: "手工拉制的劲道面条", comment: "一碗拉面走天下~", calories: "约450大卡/碗", tags: ["管饱", "实惠"], timePeriod: ["morning", "lunch"] },
  { id: 211, name: "重庆小面", type: "面点", emoji: "🌶️", description: "麻辣鲜香的重庆特色面食", comment: "山城味道~", calories: "约400大卡/碗", tags: ["重口味", "快手"], timePeriod: ["morning", "lunch"] },
  { id: 212, name: "葱油拌面", type: "面点", emoji: "🍜", description: "香葱油的拌面", comment: "上海小吃的经典~", calories: "约400大卡/碗", tags: ["主食", "便捷"], timePeriod: ["morning", "lunch"] },
  { id: 213, name: "阳春面", type: "面点", emoji: "🍜", description: "清汤寡水面条的简约", comment: "简单却经典的美味~", calories: "约320大卡/碗", tags: ["清淡", "便捷"], timePeriod: ["morning"] },
  { id: 214, name: "片儿川", type: "面点", emoji: "🍜", description: "杭州特色的鲜美面条", comment: "江南水乡的味道~", calories: "约420大卡/碗", tags: ["主食", "地方特色"], timePeriod: ["morning", "lunch"] },
  { id: 215, name: "奥灶面", type: "面点", emoji: "🍜", description: "苏州特色的浓郁面条", comment: "苏式面食的代表~", calories: "约450大卡/碗", tags: ["主食", "地方特色"], timePeriod: ["morning", "lunch"] },
  { id: 216, name: "烩面片", type: "面点", emoji: "🍜", description: "揪面片配浓郁汤底", comment: "北方家常的温暖~", calories: "约400大卡/碗", tags: ["主食", "暖胃"], timePeriod: ["morning", "lunch"] },
  { id: 217, name: "炒面", type: "面点", emoji: "🍜", description: "各种蔬菜炒面条", comment: "快手主食的好选择~", calories: "约450大卡/份", tags: ["主食", "快手"], timePeriod: ["morning", "lunch", "dinner"] },
  { id: 218, name: "焖面", type: "面点", emoji: "🍜", description: "豆角焖面的香气", comment: "北方人的家常~", calories: "约480大卡/份", tags: ["主食", "管饱"], timePeriod: ["morning", "lunch"] },
  { id: 219, name: "老北京炸酱面", type: "面点", emoji: "🍜", description: "浓郁炸酱的北京味道", comment: "皇城根下的经典~", calories: "约500大卡/碗", tags: ["主食", "京味"], timePeriod: ["morning", "lunch"] },
  { id: 220, name: "担担面", type: "面点", emoji: "🍜", description: "麻辣鲜香的担担面", comment: "四川名小吃的经典~", calories: "约400大卡/碗", tags: ["主食", "重口味"], timePeriod: ["morning", "lunch"] },
  { id: 221, name: "裤带面", type: "面点", emoji: "🍜", description: "宽如裤带的霸气面条", comment: "陕西面食的代表~", calories: "约550大卡/碗", tags: ["主食", "西北"], timePeriod: ["morning", "lunch"] },
  { id: 222, name: "油泼面", type: "面点", emoji: "🍜", description: "热油泼香的辣子面", comment: "陕西人的最爱~", calories: "约480大卡/碗", tags: ["主食", "西北"], timePeriod: ["morning", "lunch"] },
  { id: 223, name: "肉夹馍", type: "面点", emoji: "🥙", description: "酥脆白吉馍夹卤肉", comment: "西北名吃的经典~", calories: "约320大卡/个", tags: ["主食", "管饱"], timePeriod: ["morning", "lunch"] },
  { id: 224, name: "花卷", type: "面点", emoji: "🥐", description: "层层分明的咸香花卷", comment: "家常早餐的选择~", calories: "约120大卡/个", tags: ["早点", "清淡"], timePeriod: ["morning"] },
  { id: 225, name: "馒头", type: "面点", emoji: "🥖", description: "松软可口的白馒头", comment: "最朴实的主食~", calories: "约100大卡/个", tags: ["早点", "管饱"], timePeriod: ["morning"] },
  { id: 226, name: "水饺", type: "面点", emoji: "🥟", description: "皮薄馅嫩的水饺", comment: "家常主食的经典~", calories: "约150大卡/6个", tags: ["主食", "管饱"], timePeriod: ["morning", "lunch", "dinner"] },
  { id: 227, name: "馄饨", type: "面点", emoji: "🥟", description: "薄皮大馅的鲜香馄饨", comment: "南方人的早餐记忆~", calories: "约180大卡/份", tags: ["早点", "清淡"], timePeriod: ["morning"] },
  { id: 228, name: "水果沙拉", type: "轻食", emoji: "🍇", description: "新鲜水果大集合，清爽无负担", comment: "健康又美味的轻体验~", calories: "约150大卡/份", tags: ["健康", "轻体"], timePeriod: ["morning", "lunch"] },
  { id: 229, name: "三明治", type: "轻食", emoji: "🥪", description: "两片面包夹万物，营养均衡", comment: "简约不简单的美味~", calories: "约250大卡/份", tags: ["轻食", "方便"], timePeriod: ["morning", "lunch"] },
  { id: 230, name: "水果捞", type: "轻食", emoji: "🍓", description: "新鲜水果搭配酸奶，清爽解腻", comment: "清爽一夏的甜蜜~", calories: "约180大卡/份", tags: ["健康", "清爽"], timePeriod: ["lunch"] },
  { id: 231, name: "牛油果沙拉", type: "轻食", emoji: "🥑", description: "牛油果为主的新鲜沙拉", comment: "健康轻食的首选~", calories: "约280大卡/份", tags: ["健康", "轻体"], timePeriod: ["morning", "lunch"] },
  { id: 232, name: "鸡胸肉沙拉", type: "轻食", emoji: "🥗", description: "高蛋白鸡胸肉沙拉", comment: "健身达人的午餐~", calories: "约250大卡/份", tags: ["健康", "高蛋白"], timePeriod: ["morning", "lunch"] },
  { id: 233, name: "藜麦沙拉", type: "轻食", emoji: "🥗", description: "超级食材藜麦沙拉", comment: "营养全面的健康餐~", calories: "约300大卡/份", tags: ["健康", "超级食物"], timePeriod: ["morning", "lunch"] },
  { id: 234, name: "凯撒沙拉", type: "轻食", emoji: "🥬", description: "经典凯撒沙拉的清爽", comment: "西式轻食的代表~", calories: "约280大卡/份", tags: ["健康", "西式"], timePeriod: ["morning", "lunch"] },
  { id: 235, name: "希腊沙拉", type: "轻食", emoji: "🫒", description: "橄榄奶酪的希腊风味", comment: "地中海的健康~", calories: "约260大卡/份", tags: ["健康", "地中海"], timePeriod: ["morning", "lunch"] },
  { id: 236, name: "吞拿鱼沙拉", type: "轻食", emoji: "🐟", description: "低脂吞拿鱼的沙拉", comment: "高蛋白低脂肪~", calories: "约220大卡/份", tags: ["健康", "高蛋白"], timePeriod: ["morning", "lunch"] },
  { id: 237, name: "土豆沙拉", type: "轻食", emoji: "🥔", description: "绵密土豆的健康沙拉", comment: "饱腹感十足的轻食~", calories: "约240大卡/份", tags: ["健康", "饱腹"], timePeriod: ["morning", "lunch"] },
  { id: 238, name: "番茄沙拉", type: "轻食", emoji: "🍅", description: "新鲜番茄的清爽沙拉", comment: "简单却美味~", calories: "约120大卡/份", tags: ["健康", "清淡"], timePeriod: ["morning", "lunch"] },
  { id: 239, name: "鸡肉牛油果碗", type: "轻食", emoji: "🥑", description: "鸡肉牛油果的能量碗", comment: "健身餐的热门~", calories: "约380大卡/份", tags: ["健康", "高蛋白"], timePeriod: ["morning", "lunch"] },
  { id: 240, name: "三文鱼碗", type: "轻食", emoji: "🍣", description: "三文鱼配杂粮的碗", comment: "日式健康餐~", calories: "约350大卡/份", tags: ["健康", "精致"], timePeriod: ["morning", "lunch"] },
  { id: 241, name: "蔬菜汤", type: "轻食", emoji: "🥣", description: "各种蔬菜的清淡汤", comment: "刮油清肠的好选择~", calories: "约100大卡/碗", tags: ["健康", "清淡"], timePeriod: ["morning", "lunch"] },
  { id: 242, name: "南瓜汤", type: "轻食", emoji: "🎃", description: "绵密香甜的南瓜汤", comment: "暖胃又健康的美味~", calories: "约150大卡/碗", tags: ["健康", "暖胃"], timePeriod: ["morning", "lunch"] },
  { id: 243, name: "胡萝卜汁", type: "轻食", emoji: "🥕", description: "新鲜胡萝卜的果汁", comment: "护眼又健康的饮品~", calories: "约80大卡/杯", tags: ["健康", "养生"], timePeriod: ["morning", "lunch"] },
  { id: 244, name: "芹菜汁", type: "轻食", emoji: "🥬", description: "清爽的芹菜汁", comment: "刮油清肠的饮品~", calories: "约50大卡/杯", tags: ["健康", "排毒"], timePeriod: ["morning"] },
  { id: 245, name: "燕麦杯", type: "轻食", emoji: "🥣", description: "隔夜燕麦的健康杯", comment: "早餐的便捷选择~", calories: "约280大卡/份", tags: ["健康", "便捷"], timePeriod: ["morning"] },
  { id: 246, name: "希腊酸奶", type: "轻食", emoji: "🥛", description: "浓稠的希腊酸奶", comment: "高蛋白低脂肪的美味~", calories: "约180大卡/份", tags: ["健康", "高蛋白"], timePeriod: ["morning", "lunch"] },
  { id: 247, name: "清蒸西兰花", type: "轻食", emoji: "🥦", description: "清蒸西兰花的营养", comment: "蔬菜之王~", calories: "约80大卡/份", tags: ["健康", "清淡"], timePeriod: ["morning", "lunch"] },
  { id: 248, name: "清蒸鸡胸", type: "轻食", emoji: "🍗", description: "嫩滑清蒸的鸡胸肉", comment: "健身必备~", calories: "约180大卡/份", tags: ["健康", "高蛋白"], timePeriod: ["morning", "lunch"] },
  { id: 249, name: "清蒸鱼", type: "轻食", emoji: "🐟", description: "鲜嫩清蒸的鱼肉", comment: "高蛋白低脂肪~", calories: "约200大卡/份", tags: ["健康", "清淡"], timePeriod: ["morning", "lunch"] },
  { id: 250, name: "麻辣烫", type: "小吃", emoji: "🍲", description: "万物皆可烫的川味小吃，辣得过瘾", comment: "无辣不欢的快乐！", calories: "约400大卡/份", tags: ["重口味", "热闹"], timePeriod: ["lunch", "dinner"] },
  { id: 251, name: "关东煮", type: "小吃", emoji: "🍢", description: "热气腾腾的汤煮小吃，暖胃又暖心", comment: "冬日里的小确幸~", calories: "约250大卡/份", tags: ["清淡", "暖胃"], timePeriod: ["morning", "lunch", "dinner"] },
  { id: 252, name: "烤冷面", type: "小吃", emoji: "🍳", description: "铁板烤制的香软冷面，酱香四溢", comment: "夜宵摊的必点项！", calories: "约300大卡/份", tags: ["夜宵", "解馋"], timePeriod: ["dinner"] },
  { id: 253, name: "肉夹馍", type: "小吃", emoji: "🥙", description: "酥脆白吉馍夹卤香肉，香到迷糊", comment: "西北名吃的魅力！", calories: "约320大卡/个", tags: ["管饱", "实惠"], timePeriod: ["morning", "lunch"] },
  { id: 254, name: "螺蛳粉", type: "小吃", emoji: "🍜", description: "酸辣鲜香的广西特色，闻着臭吃着香", comment: "上头的味道，无法拒绝！", calories: "约400大卡/份", tags: ["重口味", "上头"], timePeriod: ["lunch", "dinner"] },
  { id: 255, name: "可乐鸡翅", type: "小吃", emoji: "🍗", description: "可乐焖煮的甜香鸡翅", comment: "甜甜咸咸就是我~", calories: "约180大卡/个", tags: ["下午茶", "解馋"], timePeriod: ["lunch", "dinner"] },
  { id: 256, name: "臭豆腐", type: "小吃", emoji: "🧈", description: "闻着臭吃着香的经典", comment: "长沙名吃的代表~", calories: "约200大卡/份", tags: ["重口味", "地方特色"], timePeriod: ["lunch", "dinner"] },
  { id: 257, name: "烤面筋", type: "小吃", emoji: "🫓", description: "孜然飘香的烤面筋", comment: "街边小吃的热门~", calories: "约80大卡/串", tags: ["夜宵", "解馋"], timePeriod: ["dinner"] },
  { id: 258, name: "鸡蛋灌饼", type: "小吃", emoji: "🥚", description: "鸡蛋香葱的灌饼", comment: "早餐摊的经典~", calories: "约250大卡/份", tags: ["早点", "管饱"], timePeriod: ["morning"] },
  { id: 259, name: "肠粉", type: "小吃", emoji: "🥟", description: "广东早餐的经典米肠", comment: "滑嫩可口的美味~", calories: "约200大卡/份", tags: ["早点", "清淡"], timePeriod: ["morning"] },
  { id: 260, name: "豆腐脑", type: "小吃", emoji: "🫘", description: "咸香或甜滑的豆腐脑", comment: "南北之争的代表~", calories: "约150大卡/碗", tags: ["早点", "清淡"], timePeriod: ["morning"] },
  { id: 261, name: "糖葫芦", type: "小吃", emoji: "🍡", description: "酸甜山楂的冰糖葫芦", comment: "冬日里的甜蜜~", calories: "约120大卡/串", tags: ["零食", "童年回忆"], timePeriod: ["dinner"] },
  { id: 262, name: "凉皮", type: "小吃", emoji: "🌶️", description: "酸辣爽口的凉皮", comment: "夏日开胃的经典~", calories: "约250大卡/份", tags: ["开胃", "清凉"], timePeriod: ["morning", "lunch"] },
  { id: 263, name: "凉面", type: "小吃", emoji: "🍜", description: "冰凉酸甜的凉面", comment: "消暑降温的美味~", calories: "约300大卡/份", tags: ["清凉", "开胃"], timePeriod: ["morning", "lunch"] },
  { id: 264, name: "凉粉", type: "小吃", emoji: "🧊", description: "清爽滑嫩的凉粉", comment: "夏日的清凉~", calories: "约150大卡/份", tags: ["清凉", "清淡"], timePeriod: ["morning", "lunch"] },
  { id: 265, name: "炸鸡柳", type: "小吃", emoji: "🍗", description: "香脆金黄的炸鸡柳", comment: "小食解馋的好选择~", calories: "约200大卡/份", tags: ["小食", "解馋"], timePeriod: ["lunch"] },
  { id: 266, name: "炸鸡排", type: "小吃", emoji: "🍗", description: "外酥里嫩的炸鸡排", comment: "香脆诱人的美味~", calories: "约280大卡/份", tags: ["小食", "解馋"], timePeriod: ["lunch"] },
  { id: 267, name: "薯条", type: "小吃", emoji: "🍟", description: "金黄酥脆的炸薯条", comment: "快餐的经典搭配~", calories: "约300大卡/份", tags: ["小食", "解馋"], timePeriod: ["lunch"] },
  { id: 268, name: "薯片", type: "小吃", emoji: "🥔", description: "薄脆咸香的薯片", comment: "追剧必备的零食~", calories: "约250大卡/包", tags: ["零食", "解馋"], timePeriod: ["lunch"] },
  { id: 269, name: "爆米花", type: "小吃", emoji: "🍿", description: "香甜可口的爆米花", comment: "看电影的最佳搭档~", calories: "约200大卡/份", tags: ["零食", "解馋"], timePeriod: ["lunch"] },
  { id: 270, name: "鸡米花", type: "小吃", emoji: "🍗", description: "小巧可爱的炸鸡米花", comment: "追剧小零食~", calories: "约250大卡/份", tags: ["小食", "解馋"], timePeriod: ["lunch"] },
  { id: 271, name: "炸鸡腿", type: "小吃", emoji: "🍗", description: "香喷喷的大鸡腿", comment: "大口吃肉的满足~", calories: "约300大卡/个", tags: ["小食", "管饱"], timePeriod: ["lunch"] },
  { id: 272, name: "鸡锁骨", type: "小吃", emoji: "🍗", description: "香酥可口的鸡锁骨", comment: "夜市的热门~", calories: "约200大卡/份", tags: ["夜宵", "解馋"], timePeriod: ["dinner"] },
  { id: 273, name: "鸡爪子", type: "小吃", emoji: "🐔", description: "Q弹有嚼劲的鸡爪", comment: "越嚼越香的美味~", calories: "约150大卡/份", tags: ["夜宵", "下酒"], timePeriod: ["dinner"] },
  { id: 274, name: "鸭脖子", type: "小吃", emoji: "🦆", description: "麻辣鲜香的鸭脖子", comment: "追剧必备的零食~", calories: "约180大卡/份", tags: ["零食", "重口味"], timePeriod: ["dinner"] },
  { id: 275, name: "小笼包", type: "包子", emoji: "🥟", description: "薄皮大馅汤汁多，一口一个满足", comment: "早餐的正确打开方式~", calories: "约200大卡/4个", tags: ["早点", "管饱"], timePeriod: ["morning"] },
  { id: 276, name: "鲜肉包子", type: "包子", emoji: "🥮", description: "松软面皮包裹鲜香肉馅，早餐好选择", comment: "小巧玲珑，美味可口~", calories: "约150大卡/个", tags: ["早点", "方便"], timePeriod: ["morning"] },
  { id: 277, name: "叉烧包", type: "包子", emoji: "🥟", description: "蜜汁叉烧馅的广式包子", comment: "粤式早茶的经典~", calories: "约200大卡/个", tags: ["早点", "粤式"], timePeriod: ["morning"] },
  { id: 278, name: "奶黄包", type: "包子", emoji: "🥮", description: "香甜奶黄馅的软包子", comment: "小朋友的最爱~", calories: "约180大卡/个", tags: ["早点", "甜点"], timePeriod: ["morning"] },
  { id: 279, name: "豆沙包", type: "包子", emoji: "🥮", description: "细腻红豆馅的甜包子", comment: "传统甜包的经典~", calories: "约170大卡/个", tags: ["早点", "甜点"], timePeriod: ["morning"] },
  { id: 280, name: "流沙包", type: "包子", emoji: "🥮", description: "咸蛋黄流沙的美味包子", comment: "港式早茶的热门~", calories: "约190大卡/个", tags: ["早点", "精致"], timePeriod: ["morning"] },
  { id: 281, name: "灌汤包", type: "包子", emoji: "🥟", description: "汤汁满满的灌汤包", comment: "开封名吃的经典~", calories: "约160大卡/个", tags: ["早点", "精致"], timePeriod: ["morning"] },
  { id: 282, name: "生煎包", type: "包子", emoji: "🥟", description: "底部酥脆的生煎包", comment: "上海早餐的代表~", calories: "约180大卡/个", tags: ["早点", "酥脆"], timePeriod: ["morning"] },
  { id: 283, name: "水煎包", type: "包子", emoji: "🥟", description: "水煎双吃的美味包子", comment: "山东早餐的经典~", calories: "约170大卡/个", tags: ["早点", "管饱"], timePeriod: ["morning"] },
  { id: 284, name: "大肉包", type: "包子", emoji: "🥟", description: "皮薄馅大的鲜肉包", comment: "管饱实在的选择~", calories: "约250大卡/个", tags: ["早点", "管饱"], timePeriod: ["morning"] },
  { id: 285, name: "粉丝包", type: "包子", emoji: "🥟", description: "粉丝肉馅的粉丝包", comment: "安徽小吃的经典~", calories: "约160大卡/个", tags: ["早点", "清淡"], timePeriod: ["morning"] },
  { id: 286, name: "梅菜包", type: "包子", emoji: "🥟", description: "梅干菜扣肉的香包", comment: "浙江早餐的特色~", calories: "约170大卡/个", tags: ["早点", "咸香"], timePeriod: ["morning"] },
  { id: 287, name: "香菇青菜包", type: "包子", emoji: "🥬", description: "香菇青菜的素馅包", comment: "清淡健康的选择~", calories: "约140大卡/个", tags: ["早点", "素食"], timePeriod: ["morning"] },
  { id: 288, name: "紫薯包", type: "包子", emoji: "🍠", description: "紫薯馅的香甜包子", comment: "颜值与美味并存~", calories: "约160大卡/个", tags: ["早点", "甜点"], timePeriod: ["morning"] },
  { id: 289, name: "糯米鸡", type: "包子", emoji: "🍚", description: "荷叶包裹的糯米鸡", comment: "粤式早茶的经典~", calories: "约280大卡/个", tags: ["早点", "粤式"], timePeriod: ["morning"] },
  { id: 290, name: "肉龙", type: "包子", emoji: "🐉", description: "长条形的肉馅卷", comment: "北京小吃的经典~", calories: "约300大卡/份", tags: ["早点", "管饱"], timePeriod: ["morning"] },
  { id: 291, name: "糖三角", type: "包子", emoji: "🔺", description: "红糖馅的三角包子", comment: "童年早餐的甜蜜~", calories: "约150大卡/个", tags: ["早点", "甜点"], timePeriod: ["morning"] },
  { id: 292, name: "窝窝头", type: "包子", emoji: "🌽", description: "玉米面的健康窝头", comment: "粗粮养生的选择~", calories: "约120大卡/个", tags: ["早点", "养生"], timePeriod: ["morning"] },
  { id: 293, name: "粘豆包", type: "包子", emoji: "🟡", description: "粘软香甜的豆包", comment: "东北小吃的经典~", calories: "约180大卡/个", tags: ["早点", "甜点"], timePeriod: ["morning"] },
  { id: 294, name: "菜包", type: "包子", emoji: "🥬", description: "各种蔬菜馅的素包", comment: "清淡健康的选择~", calories: "约140大卡/个", tags: ["早点", "素食"], timePeriod: ["morning"] },
  { id: 295, name: "豆腐包", type: "包子", emoji: "🧈", description: "豆腐馅的清香包子", comment: "素食主义者的首选~", calories: "约130大卡/个", tags: ["早点", "素食"], timePeriod: ["morning"] },
  { id: 296, name: "煎饼果子", type: "煎饼", emoji: "🥞", description: "酥脆薄饼配鸡蛋香肠，街头美食扛把子", comment: "元气满满的一天~", calories: "约350大卡/份", tags: ["早点", "实惠"], timePeriod: ["morning"] },
  { id: 297, name: "手抓饼", type: "煎饼", emoji: "🫓", description: "层层分明的酥脆饼皮，卷啥都香", comment: "早餐界的百搭之王！", calories: "约280大卡/份", tags: ["早点", "快手"], timePeriod: ["morning"] },
  { id: 298, name: "杂粮煎饼", type: "煎饼", emoji: "🥞", description: "杂粮面糊的香脆煎饼", comment: "健康早餐的选择~", calories: "约280大卡/份", tags: ["早点", "健康"], timePeriod: ["morning"] },
  { id: 299, name: "山东杂粮煎饼", type: "煎饼", emoji: "🥞", description: "正宗山东风味的杂粮煎饼", comment: "酥脆可口的美味~", calories: "约300大卡/份", tags: ["早点", "管饱"], timePeriod: ["morning"] },
  { id: 300, name: "鸡蛋灌饼", type: "煎饼", emoji: "🥚", description: "鸡蛋灌入饼中的香脆", comment: "早餐摊的热门~", calories: "约260大卡/份", tags: ["早点", "管饱"], timePeriod: ["morning"] },
  { id: 301, name: "酱香饼", type: "煎饼", emoji: "🫓", description: "酱香浓郁的香脆饼", comment: "街边小吃的经典~", calories: "约250大卡/份", tags: ["早点", "咸香"], timePeriod: ["morning"] },
  { id: 302, name: "葱油饼", type: "煎饼", emoji: "🧅", description: "葱香四溢的香脆饼", comment: "简单却美味的早餐~", calories: "约220大卡/份", tags: ["早点", "咸香"], timePeriod: ["morning"] },
  { id: 303, name: "千层饼", type: "煎饼", emoji: "🫓", description: "层层叠叠的香脆饼", comment: "酥脆可口的美味~", calories: "约240大卡/份", tags: ["早点", "酥脆"], timePeriod: ["morning"] },
  { id: 304, name: "梅干菜饼", type: "煎饼", emoji: "🥬", description: "梅干菜香的薄脆饼", comment: "浙江小吃的经典~", calories: "约200大卡/份", tags: ["早点", "咸香"], timePeriod: ["morning"] },
  { id: 305, name: "馅饼", type: "煎饼", emoji: "🥙", description: "各种馅料的香脆饼", comment: "北方面食的代表~", calories: "约280大卡/个", tags: ["早点", "管饱"], timePeriod: ["morning"] },
  { id: 306, name: "韭菜盒子", type: "煎饼", emoji: "🥬", description: "韭菜鸡蛋馅的香脆盒", comment: "春季时令的美味~", calories: "约250大卡/个", tags: ["早点", "咸香"], timePeriod: ["morning"] },
  { id: 307, name: "萝卜丝饼", type: "煎饼", emoji: "🥕", description: "萝卜丝馅的香脆饼", comment: "江浙小吃的经典~", calories: "约180大卡/个", tags: ["早点", "清淡"], timePeriod: ["morning"] },
  { id: 308, name: "土豆丝饼", type: "煎饼", emoji: "🥔", description: "土豆丝馅的香脆饼", comment: "土豆控的最爱~", calories: "约200大卡/个", tags: ["早点", "管饱"], timePeriod: ["morning"] },
  { id: 309, name: "西葫芦饼", type: "煎饼", emoji: "🥒", description: "西葫芦丝的软嫩饼", comment: "清淡健康的选择~", calories: "约160大卡/个", tags: ["早点", "清淡"], timePeriod: ["morning"] },
  { id: 310, name: "紫菜饼", type: "煎饼", emoji: "🫒", description: "紫菜芝麻的香脆饼", comment: "海的味道~", calories: "约180大卡/份", tags: ["早点", "海味"], timePeriod: ["morning"] },
  { id: 311, name: "锅盔", type: "煎饼", emoji: "🫓", description: "薄脆香酥的大锅盔", comment: "四川名吃的经典~", calories: "约200大卡/个", tags: ["早点", "管饱"], timePeriod: ["morning"] },
  { id: 312, name: "鸡蛋饼", type: "煎饼", emoji: "🥚", description: "鸡蛋打散的软嫩饼", comment: "简单早餐的经典~", calories: "约180大卡/份", tags: ["早点", "快手"], timePeriod: ["morning"] },
  { id: 313, name: "玉米饼", type: "煎饼", emoji: "🌽", description: "玉米面的香甜软饼", comment: "粗粮的健康选择~", calories: "约150大卡/个", tags: ["早点", "健康"], timePeriod: ["morning"] },
  { id: 314, name: "红薯饼", type: "煎饼", emoji: "🍠", description: "红薯泥的香甜软饼", comment: "甜而不腻的美味~", calories: "约160大卡/个", tags: ["早点", "甜点"], timePeriod: ["morning"] },
  { id: 315, name: "南瓜饼", type: "煎饼", emoji: "🎃", description: "南瓜泥的软糯香饼", comment: "秋季时令的甜蜜~", calories: "约150大卡/个", tags: ["早点", "甜点"], timePeriod: ["morning"] }
];

const foodTypes = [
  { name: "火锅", emoji: "🍲", color: "#FF6B6B", periods: ["lunch", "dinner"] },
  { name: "烧烤", emoji: "🍖", color: "#FF8C00", periods: ["lunch", "dinner"] },
  { name: "甜品", emoji: "🍰", color: "#FF69B4", periods: ["all"] },
  { name: "奶茶", emoji: "🧋", color: "#DEB887", periods: ["all"] },
  { name: "快餐", emoji: "🍔", color: "#FFA500", periods: ["all"] },
  { name: "日料", emoji: "🍣", color: "#FF6347", periods: ["lunch", "dinner"] },
  { name: "韩料", emoji: "🥘", color: "#228B22", periods: ["lunch", "dinner"] },
  { name: "川菜", emoji: "🌶️", color: "#DC143C", periods: ["lunch", "dinner"] },
  { name: "面点", emoji: "🍜", color: "#F4A460", periods: ["all"] },
  { name: "轻食", emoji: "🥗", color: "#90EE90", periods: ["all"] },
  { name: "咖啡", emoji: "☕", color: "#8B4513", periods: ["morning", "all"] },
  { name: "面包", emoji: "🥐", color: "#DAA520", periods: ["morning", "all"] },
  { name: "包子", emoji: "🥟", color: "#FFD700", periods: ["morning", "all"] },
  { name: "煎饼", emoji: "🌯", color: "#CD853F", periods: ["morning", "all"] },
  { name: "小吃", emoji: "🍢", color: "#FF4500", periods: ["all"] }
];

const getTimePeriod = () => {
  const hour = new Date().getHours();
  if (hour >= 5 && hour < 10) return "morning";
  if (hour >= 10 && hour < 17) return "lunch";
  return "dinner";
};

const getTimePeriodName = (period) => {
  const names = {
    morning: "早餐",
    lunch: "午餐",
    dinner: "晚餐",
    all: "全天"
  };
  return names[period] || "美食";
};

const filterFoodsByTypesAndTime = (selectedTypes, timePeriod) => {
  let filtered = foods;

  if (timePeriod && timePeriod !== 'all') {
    filtered = filtered.filter(food =>
      food.timePeriod.includes(timePeriod)
    );
  }

  if (selectedTypes && selectedTypes.length > 0) {
    filtered = filtered.filter(food =>
      selectedTypes.includes(food.type)
    );
  }

  return filtered;
};

const getTypesForPeriod = (period) => {
  if (period === 'all') {
    return foodTypes;
  }
  return foodTypes.filter(type => 
    type.periods.includes(period) || type.periods.includes('all')
  );
};

const getRandomFood = (selectedTypes) => {
  const timePeriod = getTimePeriod();
  const availableFoods = filterFoodsByTypesAndTime(selectedTypes, timePeriod);
  const randomIndex = Math.floor(Math.random() * availableFoods.length);
  return availableFoods[randomIndex];
};

const getShareText = (food) => {
  const texts = [
    `今天的快乐源泉就是这碗${food.name}！`,
    `${food.emoji} ${food.name}，我宣布这是今日最佳！`,
    `吃货的日常：${food.name}安排上~ ${food.emoji}`,
    `今日份美食已到账：${food.name}！`,
    `${food.name}在手，天下我有！${food.emoji}`
  ];
  return texts[Math.floor(Math.random() * texts.length)];
};

module.exports = {
  foods,
  foodTypes,
  getTimePeriod,
  getTimePeriodName,
  getRandomFood,
  filterFoodsByTypesAndTime,
  getTypesForPeriod,
  getShareText
};
